version: '3.1'
services:
  db:
    image: mysql:8
    container_name: db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: sintez
      MYSQL_PASSWORD: sintez
      MYSQL_ROOT_PASSWORD: sintez
    restart: always
    ports:
      - "54321:3306"
    volumes:
      - ./django:/var/lib/mysql:Z
  web:
    build: ./book_site
    container_name: web
    hostname: web
    env_file:
      - ./django_env.env
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "12333:8000"
    depends_on:
      - db
    volumes:
      - ./book_site/media:/web_django/media:Z
#      - ./book_site:/web_django:Z
